apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-platform.fullname" . }}-control-plane
  labels:
    {{- include "docker-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.controlPlane.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "docker-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
